# Generated by Django 4.2.7 on 2023-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_date',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=20),
        ),
    ]
